services:
  twentyfourseven:
    build: .
    ports:
      - "8088:80"      # Nginx proxy (main port)
      - "33000:3000"   # Server port
      - "33001:3001"   # Web port
    environment:
      - PORT=3000
      - WEB_PORT=3001
      - BETTER_AUTH_SECRET=your-secure-secret-key-change-this
      # External HTTP port (nginx proxy) - automatically configures all URLs
      - EXTERNAL_HTTP_PORT=8088
      # External port mappings for startup messages
      - EXTERNAL_NGINX_PORT=8088
      - EXTERNAL_SERVER_PORT=33000
      - EXTERNAL_WEB_PORT=33001
    # Optional: Uncomment to persist data and serve static files
    # volumes:
    #   - ./data:/app/database
    #   - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 